# Generated by Django 4.0.4 on 2022-05-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
    ]
