# Generated by Django 4.0.4 on 2022-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220517_0435'),
    ]

    operations = [
    ]
