# Generated by Django 4.0.4 on 2022-05-17 02:50

from django.db import migrations

def populate_languages(apps, schemaeditor):
    languages = [
            {
                "key": "EN",
                "name": "English"

            },
            {
                 "key": "ES",
                 "name": "Espanol"


            },
            {
                "key": "DE",
                "name": "Deutsch"


            },
            {
                "key": "PT",
                "name": "Portugues"

            }
        ]
    Language = apps.get_model('accounts', 'Language')
    for language in languages:
        lang_obj = Language(
            key=language.get("key"),
            name=language.get("name")
            )
        lang_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_language_customuser_preferred_language'),
    ]

    operations = [
        migrations.RunPython(populate_languages)
    ]
